### ISSUE TITLE
Scope out Electron app migration

### ISSUE THREAD

**Issue by artisonian** [artisonian/erudite#10]
What would it take to convert this into an Electron app? I can imagine being able to open Markdown documents and seeing the results either inline or in a separate pane. That would imply an API for rendering output into the view. But for exploration, maybe console output is sufficient.

**Comment by artisonian** [comment]
MVP:
- [ ] Open Markdown files from file system
- [ ] Load modules
- [ ] Output to `BrowserWindow` console

**Comment by hlapp** [comment]
BTW just in case you weren't aware, there is [Jupyter Notebooks](http://jupyter.org) for mixing Markdown with code and allowing code to be evaluated inline. There are kernels for different languages, including one for NodeJS.  It's web-based, not an app, but can (and usually would) run locally.

**Comment by artisonian** [comment]
Cool! Didn't know the project expanded beyond Python.
